### ISSUE TITLE
No providers found on class path

### ISSUE THREAD

**Issue by duncanmak** [Dyescape/kotlin-maven-symbol-processing#106]
I get this error, my build is working with `kapt`.

```
INFO] Exit code: COMPILATION_ERROR
[ERROR] [ksp] No providers found in processor classpath.
```

The diff looks like this:

```
         <artifactId>kotlin-maven-plugin</artifactId>
         <version>${kotlin.version}</version>
         <extensions>true</extensions>
-        <executions>
-          <execution>
-            <id>kapt</id>
-            <goals>
-              <goal>kapt</goal>
-            </goals>
-            <configuration>
-              <annotationProcessorPaths>
-                <path>
-                  <groupId>org.graalvm.truffle</groupId>
-                  <artifactId>truffle-dsl-processor</artifactId>
-                  <version>${graalvm.version}</version>
-                </path>
-              </annotationProcessorPaths>
-            </configuration>
-          </execution>
-        </executions>
+        <configuration>
+          <compilerPlugins>
+            <compilerPlugin>ksp</compilerPlugin>
+          </compilerPlugins>
+        </configuration>
+        <dependencies>
+          <dependency>
+            <groupId>com.dyescape</groupId>
+            <artifactId>kotlin-maven-symbol-processing</artifactId>
+            <version>1.6</version>
+          </dependency>
+          <dependency>
+            <groupId>org.graalvm.truffle</groupId>
+            <artifactId>truffle-dsl-processor</artifactId>
+            <version>${graalvm.version}</version>
+          </dependency>
+        </dependencies>
```

**Comment by fxshlein** [comment]
Hi! Does the `truffle-dsl-processor` provide a KSP implementation? I couldn't find one, but I'm not familiar with truffle, so I might be missing something.

KSP and KAPT are two very different APIs, and as far as I know KSP doesn't support java annotation processors, so truffle would need to support KSP first by writing a symbol processor. It's really hard to find information on this, and all the KSP docs really do sound like you can use it for java annotation processors, to the point where even I am unsure now 😄

**Comment by fxshlein** [comment]
I did some digging, and it really does seem like KSP doesn't support java annotation processors. The `META-INF/services` directory in the `truffle-dsl-processor` jar file also only contains `javax.annotation.processing.Processor` services. KSP needs a `com.google.devtools.ksp.processing.SymbolProcessorProvider`, so I don't think truffle supports KSP.

This repo is only a very slim wrapper that makes KSP run in Maven, so we can't really provide any support for KSP itself.

I think for now you just have to keep using KAPT. You might need to create an issue with graal/truffle to support KSP. Alternatively, you might have some luck on the [kotlinlang slack](https://slack.kotlinlang.org), they have #ksp and #kapt channels, and the people there might know some tricks to get KSP working with java annotation processors.

Sorry I can't be of more help 🫤

**Comment by duncanmak** [comment]
Thank you! I didn't know that KSP doesn't support java annotation processors, I thought it was a complete replacement for kapt.
