### ISSUE TITLE
Pass custom options to the KSP plugin

### ISSUE THREAD

**Issue by teras** [Dyescape/kotlin-maven-symbol-processing#24]
Hello.
Is it possible to pass custom options to the KSP plugin?
I tried to do something like

```
            <pluginOptions>
                <option>ksp:hello=false</option>
            </pluginOptions>
```

but it breaks with the message
```
[ERROR] Unsupported plugin option: com.google.devtools.ksp.symbol-processing:hello=true
```
which makes sense, since I haven't put any special care as it seems to define this option.
I even tried to add it at the `getPluginOptions` function "manually", but this still didn''t work...

Any hints what to do?

**Comment by fxshlein** [comment]
Hey!

Its a bit hard to tell what the intended way to achieve this is from the documentation, however this might be interesting:
https://kotlinlang.org/docs/ksp-command-line.html

Especially these two lines in the code snippet at the end:
```
-P $KSP_PLUGIN_OPT:apoption=key1=value1 \
-P $KSP_PLUGIN_OPT:apoption=key2=value2 \
```

This suggests to me that it should actually be `ksp:apoption=hello=false`.

`apoption` also is in the KSP source code [here](https://github.com/google/ksp/blob/main/common-util/src/main/kotlin/com/google/devtools/ksp/KspOptions.kt#L177), and you can see how the options are parsed into the actual key-value pairs at the bottom of the same file [here](https://github.com/google/ksp/blob/main/common-util/src/main/kotlin/com/google/devtools/ksp/KspOptions.kt#L269).

**Comment by teras** [comment]
IT WORKS!!!

I'd suggest to add this on the documentation.
Maybe more people will have the same problem as me.

If you are busy, I can make a PR with this information. 
THANK YOU AGAIN!

**Comment by fxshlein** [comment]
Nice! And great so see someone is actually using this 😄
