### ISSUE TITLE
Add maven plugin to project

### ISSUE THREAD

**Issue by i-walker** [Dyescape/kotlin-maven-symbol-processing#26]
Here I've been trying to add this plugin to a [project](https://github.com/arrow-kt/Arrow-Maven-Template/runs/5998286731?check_suite_focus=true), but it didn't seem to work, what repository definition is missing, or is there something in the configurations that I am missing. The PR is here https://github.com/arrow-kt/Arrow-Maven-Template/pull/17

There is a similar setup [here](https://github.com/arrow-kt/Arrow-JVM-Template/blob/optics-setup/build.gradle.kts) using Gradle, which works fine 

Any feedback or help is welcome 🙏🏾

**Comment by fxshlein** [comment]
Hi!

This project is hosted on GitHub packages: https://github.com/Dyescape/kotlin-maven-symbol-processing/packages/1096299

There is a page from GitHub about how to set up packages [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry), however the system is pretty terrible, as it does not allow anonymous access, so every user would have to configure an access token in their `settings.xml`.

There is an entire thread about very many people wanting anonymous access to open source packages here, sadly I have given up hope this will ever happen: https://github.community/t/download-from-github-package-registry-without-authentication/14407/147

Given that this packages now seems to be used by some people we'll look into just publishing it to maven central (or perhaps a public JFrog repo) later today, I'll update you later!

**Comment by i-walker** [comment]
Thanks @fxshlein :D

**Comment by fxshlein** [comment]
@i-walker The latest release is now available in maven-central! 🎉

Sites like mvnrepository.com or search.maven.org will apparently take [up to four hours](https://central.sonatype.org/publish/publish-guide/#releasing-to-central) to also reflect this, but maven should already be able to resolve the artifact:
https://repo1.maven.org/maven2/com/dyescape/kotlin-maven-symbol-processing/1.2

**Comment by i-walker** [comment]
awesome Thanks ☺️🙌🏾🙌🏾 
Good to be closed now

**Comment by fxshlein** [comment]
No problem! Glad to help 🙂
