### ISSUE TITLE
Clashes with allopen plugin

### ISSUE THREAD

**Issue by Gzernov** [Dyescape/kotlin-maven-symbol-processing#40]
Hi, when there is a dependency on allopen plugin project doesn't build with error `java.lang.IllegalStateException: The provided plugin org.jetbrains.kotlin.allopen.AllOpenComponentRegistrar is not compatible with this version of compiler
`
I checked that kotlin version is set to 1.6.20 across the project. Not sure if it's an issue of ksp itself

(From maven debug output)
`
[DEBUG] Options for plugin ksp: [classOutputDir: ~/myProject/target/classes, javaOutputDir: ~/myProject/target/generated-sources/ksp-java, kotlinOutputDir: ~/myProject/target/generated-sources/ksp, resourceOutputDir: ~/myProject/target/classes, projectBaseDir: ~/myProject, kspOutputDir: ~/myProject/target/ksp, apclasspath: ~/.m2/repository/org/jetbrains/kotlin/kotlin-maven-allopen/1.6.20/kotlin-maven-allopen-1.6.20.jar:~/.m2/repository/com/dyescape/kotlin-maven-symbol-processing/1.2/kotlin-maven-symbol-processing-1.2.jar, cachesDir: ~/.m2/repository/.cache/ksp, withCompilation: true, kotlinOutputDir: /qwe]
`
I tried to remove allopen from the classpath changing `constructProcessorClassPath` method, but that didn't help

On a side note list of options is being appended, instead of replacing existing value. See kotlinOutputDir being duplicated

**Comment by MrDienns** [comment]
Hey there,

This issue has been addressed, but a fix has not been released yet. We'll release a new version of the plugin later today. Stay tuned 🚀

**Comment by fxshlein** [comment]
Hi @Gzernov!

We just released a fix in version `1.2.1`, please let us know if it fixed the issue for you! 🙂

**Comment by Gzernov** [comment]
Thanks a lot! I confirm that the issue was fixed and plugin works as expected.
