### ISSUE TITLE
Test sources are generated in the wrong directory

### ISSUE THREAD

**Issue by Gzernov** [Dyescape/kotlin-maven-symbol-processing#41]
Currently, they are generated into `/target/generated-sources/ksp` instead of `/target/generated-test-sources/ksp`

**Comment by fxshlein** [comment]
Hi! This issue should be fixed with the newly released version 1.3.

**Comment by MrDienns** [comment]
Hey there, going to close this under the assumption that the released 1.3 solves the issue. Please re-open the issue if the issue remains.

**Comment by Gzernov** [comment]
Hi, sorry for the late reply. Now KSP generates files in the proper location, thank you very much!

One more thing, we are using KSP only for generating test code, do you think it's possible to not apply KSP plugin to the main code? It would save some compile time.
