### ISSUE TITLE
Plugin options append options, instead of replacing 

### ISSUE THREAD

**Issue by Gzernov** [Dyescape/kotlin-maven-symbol-processing#42]
Example given in the README doesn't work, when trying to set 
`
<pluginOptions>
    <option>ksp:kotlinOutputDir=/my/output/dir</option>
</pluginOptions>
`
Build fails with error of duplicate `ksp:kotlinOutputDir` option (enabling debug output for maven hints that default value is not being overridden with the new one)

**Comment by fxshlein** [comment]
Hi! Sorry for the delay, we'll make a release later that should fix this Issue.

**Comment by fxshlein** [comment]
Hi again! We've now released version 1.3 which should resolve this issue.

(Also gonna reopen this, GitHub closed it because the PR was merged)

**Comment by MrDienns** [comment]
@Gzernov have you been able to test the new 1.3 version? If so, please let us know if it solved your issue

**Comment by MrDienns** [comment]
Hey there, going to close this under the assumption that the released 1.3 solves the issue. Please re-open the issue if the issue remains.

**Comment by Gzernov** [comment]
Sorry for the late reply. I tested the mentioned use case and it works now, thank you very much!
